platform :ios, '15.6'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_install_all_ios_pods(flutter_application_path)
  symlinks_dir = File.join(flutter_application_path, '.symlinks', 'plugins')
  Dir.glob(File.join(symlinks_dir, '*', 'ios')).each do |pod_dir|
    pod File.basename(File.dirname(pod_dir)), :path => pod_dir
  end
end

target 'Runner' do
  use_frameworks!

  flutter_install_all_ios_pods(File.dirname(File.realpath(__FILE__)))

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '5.0'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.6'
      end
    end
  end
end
